# Generated by Django 5.1.6 on 2025-03-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_userbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
